format = """ $os$character$directory$git_branch$git_status"""
right_format = """$python$nodejs$rust$golang$php$java"""

add_newline = false

[os]
disabled = false
style = "bold blue"
format = "[$symbol]($style) "

[os.symbols]
Macos = " "
Fedora = " "
Arch = " "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
format = "$symbol "

[directory]
truncation_length = 1
truncate_to_repo = false
style = "bold cyan"
format = "[$path]($style) "

[git_branch]
format = "[git:\\(](bold blue)[$branch](bold red)[\\)](bold blue)"
symbol = ""

[git_status]
format = '([ ✗](bold yellow)$all_status) '
style = "bold yellow"
conflicted = "\u200B"
ahead = "\u200B"
behind = "\u200B"
diverged = "\u200B"
untracked = "\u200B"
stashed = ""
modified = "\u200B"
staged = "\u200B"
renamed = "\u200B"
deleted = "\u200B"

[python]
symbol = " "
style = "bold blue"
format = "[$symbol $virtualenv]($style) "
disabled = false

[lua]
format = '[$symbol($version )]($style)'
symbol = ' '

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol $version]($style) "
version_format = "${raw}"
disabled = false

[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol $version]($style) "
version_format = "${raw}"
disabled = false

[haskell]
style = 'blue'
symbol = ' '

[rust]
symbol = " "
style = "bold red"
format = "[$symbol $version]($style) "
version_format = "${raw}"
disabled = false

[php]
symbol = " "
style = "bold magenta"
format = "[$symbol $version]($style) "
version_format = "${raw}"
disabled = false

[java]
symbol = " "
style = "bold blue"
format = "[$symbol $version]($style) "
version_format = "${raw}"
disabled = false

[ruby]
symbol = ' '
style = 'blue'
format = "[$symbol $version]($style) "

[cmd_duration]
min_time = 3_000
format = "[$duration]($style) "
style = "bold yellow"
